### ISSUE TITLE
Remove deleted pages when updating online HTML

### ISSUE THREAD

**Issue by Mariatta** [python/docsbuild-scripts#10]
Based on discussions in: https://github.com/python/devguide/issues/114

Seems like docsbuild script doesn't remove html for docs that have been deleted.

Thanks @ned-deily  and @zware  for pointing me this way.

**Comment by JulienPalard** [comment]
I took a rapid look, current script uses a `cp -a`, using an `rsync -a --delete-delay` would correctly old files.

**Comment by JulienPalard** [comment]
Merged this a few hours ago, it should no longer happen.

logs from `docs.iad1.psf.io`:
```
[…]
DEBUG:2017-08-30 15:07:58,378:Running command 'rsync -a --delete-delay /srv/docsbuild/devguide/build/html/ /srv/docs.python.org/devguide'
[…]
```

**Comment by Mariatta** [comment]
Yay! Thanks @JulienPalard :taco:
