### ISSUE TITLE
Build time

### ISSUE THREAD

**Issue by JulienPalard** [python/docsbuild-scripts#106]
I ran a quick test on docs.p.o, now that 3.10 doc can be compiled in parallel, for a single build (one language, one version) :

HTML only it takes 2mn in parallel vs 5mn single threaded.

Full (with pdf, epub, texinfo ,,,) it takes 26mn in parllel and 38mn single threaded, it boils down to:
  - html 2%
  - text 2%
  - A4 latex 27%
  - letter latex 29%
  - epub 13%
  - texinfo 25%

I think it would be interesting to dive into this to see if it can be enhanced.

**Comment by hugovk** [comment]
This can be closed in favour of the newer https://github.com/python/docsbuild-scripts/issues/169.
