### ISSUE TITLE
After a major release we miss a PURGE on documentation_options.js

### ISSUE THREAD

**Issue by JulienPalard** [python/docsbuild-scripts#118]
If https://docs.python.org/3/_static/documentation_options.js is nor purged, the page displays the proper version but the JS tells another one, so the version switcher picks the wrong version, leading to some confusion.

**Comment by JulienPalard** [comment]
For the record:

    curl -XPURGE https://docs.python.org/{en,es,fr,id,ja,ko,pt-br,zh-cn,zh-tw,pl}/{2.7,3.5,3.6,3.7,3.8,3.9,3.10}/_static/documentation_options.js

does it for all versions and all languages.

**Comment by AA-Turner** [comment]
The `purge()` function now purges all changed files.

A
