### ISSUE TITLE
Deleted file still on 3.11 docs

### ISSUE THREAD

**Issue by hugovk** [python/docsbuild-scripts#124]
Looks like https://github.com/python/docsbuild-scripts/issues/10 has happened again, this time for 3.11.

https://github.com/python/cpython/pull/28117/files deleted `Doc/library/binhex.rst` but it's still online at https://docs.python.org/3.11/library/binhex.html (with an old "Last updated on Sep 02, 2021"). The front page is up to date ("Last updated on Feb 10, 2022")

(Re: https://discuss.python.org/t/pep-594-take-2-removing-dead-batteries-from-the-standard-library/13508/13?u=hugovk)

Like https://github.com/python/docsbuild-scripts/pull/28, perhaps the dev docs builds should also use `rsync` instead of `cp`? It's fairly common for modules to be deleted during the alpha.

**Comment by JulienPalard** [comment]
Hi, thanks for reporting it!

It was due to https://github.com/python/docsbuild-scripts/issues/122, which is fixed.

After the fix has been deployed, it took some time to really dissapear from the caches.

But it's now gone.
