### ISSUE TITLE
Show "PDF are currently being built" instead of a 404

### ISSUE THREAD

**Issue by JulienPalard** [python/docsbuild-scripts#127]
From an idea of @Mariatta, when we generate the HTML only for a new branch, we could generate a static HTML page containing a nice message like:

> This PDF file is currently being built, please try again in a few moments.

It would allow to split again fast HTML build and delayed PDF builds without having the old flood of "the PDF are broken!" in docs@ mailing list.

**Comment by hugovk** [comment]
Can this be closed after the merge of https://github.com/python/psf-salt/pull/236?

**Comment by JulienPalard** [comment]
Oh yes :)
