### ISSUE TITLE
documentation_options.js not invalidated when symlink changes

### ISSUE THREAD

**Issue by JulienPalard** [python/docsbuild-scripts#128]
https://docs.python.org/dev/_static/documentation_options.js were not purged from the fastly caches when docsbuild script changed /dev/ symlink to point to 3.12 (so the dropdown menu were thinking it was 3.11).

**Comment by AA-Turner** [comment]
Closed in b3c3137efb04c789a60b4ceb65fbb0ad46370f4b.

A
