### ISSUE TITLE
Need to add "blurb" to installed packages for docsbuild on docs.iad1.psf.io

### ISSUE THREAD

**Issue by ned-deily** [python/docsbuild-scripts#14]
@larryhastings has been working hard on solving the long-standing problem of managing updates to the Misc/NEWS file in the cpython repos.  That file in each branch is an input to the corresponding documentation build to produce its changelog (e.g. https://docs.python.org/3.6/whatsnew/changelog.html).  With the changes that Larry is now rolling out to the various branches (already in 3.5), the Docs build now has a dependency on a new utility called `blurb` (https://pypi.python.org/pypi/blurb/1.0.4).  We need to make sure that `blurb` is now on the PATH during the Docs build.  I'm not quite sure what is the best way to accomplish this on docs.iad1.psf.io.  The Makefile currently expects `blurb` to be installed in the `python3` that is available in the Docs build, whether that is a "system" python3 or a venv python3 is a question.  So pip installing `blurb` into the right python3 should solve the problem.  See the `build` recipe in the cpython `Doc/Makefile` for details (currently 3.5 has been updated but others will follow soon).

The specific pip requirement should be:
`blurb>=1.0.4`

This is a high priority item because the website docs break as these changes are pushed into the various branches.

**Comment by ned-deily** [comment]
@ewdurbin @benjaminp

**Comment by ewdurbin** [comment]
@ned-deily salt automatically pulls deps from the requirements.txt file in this repo:

https://github.com/python/psf-salt/blob/master/salt/docs/init.sls#L38-L46

**Comment by ewdurbin** [comment]
So I believe we should just need to add `blurb` here: https://github.com/python/docsbuild-scripts/blob/master/requirements.txt

I'll double check the PATH exposed to cron jobs...

**Comment by ned-deily** [comment]
Yep, assuming /srv/docsbuild/scripts/requirements.txt gets updated from there.  Thanks!

**Comment by JulienPalard** [comment]
So blurb is installed but I missed a step: the docsbuild script venv is running Python 2.7.

As nothing is blocking us for using Python 3 (not knowing it was 2.7, I always used a Python 3 venv locally and it works perfectly) we should first upgrade this venv to Python 3, then modify docsbuild script to pass this venv' python to Makefile so blurb will be available from within it.

See: https://github.com/python/psf-salt/issues/109

**Comment by JulienPalard** [comment]
Thanks to @ewdurbin we now have a Python 3 venv available https://github.com/python/psf-salt/pull/110/files with the requirements I updated in https://github.com/python/docsbuild-scripts/pull/15.

But the docs server provides Python 3.4 and blurb has been written in 3.6, may support 3.5 but is not compatible with 3.4:

```
  File "blurb/blurb.py", line 1049
    subprocess.run(["git", "add", *git_add_files], stdout=subprocess.PIPE, stderr=subprocess.PIPE).check_returncode()
                                         ^
SyntaxError: can use starred expression only as assignment target
```

I have not tested it extensively there may be other incompatibilities.

**Comment by JulienPalard** [comment]
I no longer see blurb missing errors in logs.
