### ISSUE TITLE
Note on progress on not completed translations

### ISSUE THREAD

**Issue by m-aciek** [python/docsbuild-scripts#148]
I would like to propose adding a note to non-English docs which are not fully translated saying "This documentation is translated into [Polish] in [10.12]%. Consider joining the translations effort (link)."[1] That would set expectation for encountering not translated paragraphs and about the quantity of translated materials in general. Second effect (but not main) would be recruiting new translators by showing a link to translations guide/readme.

<img width="1095" alt="Zrzut ekranu 2023-02-26 o 03 47 54" src="https://user-images.githubusercontent.com/9288014/221389458-6670e41a-3e69-4d6d-bcea-70789a47e0a2.png">
<img width="1082" alt="Zrzut ekranu 2023-02-26 o 03 52 06" src="https://user-images.githubusercontent.com/9288014/221389607-287f9fc3-fdb9-47a4-abd9-6b8f12dc49ea.png">

The second, recruitment sentence, is debatable. Maybe the first sentence would suffice.

Original idea by @kachinger.

[1] The link would be https://github.com/python/python-docs-xx

**Comment by egeakman** [comment]
It would be helpful to inform users that certain paragraphs may not be fully translated to avoid confusion and feedback such as "Why are there English words everywhere? I thought this was a complete translation."

As the Turkish translation team, we are currently facing challenges in recruiting enough translators to keep up with the workload. This may be an issue for other translation teams as well. Adding a "Join the translation efforts" section with a link to the translation README could help address this problem.

By the way, do you have any ideas on how the progress text can be implemented, specifically in terms of calculating the progress percentage? I'm assuming we want to track progress per file, but I'm not sure about the specifics. There is a package called [``potodo``](https://pypi.org/p/potodo) that can track the progress of .po files, maybe it might be relevant? Any thoughts?

**Comment by m-aciek** [comment]
> By the way, do you have any ideas on how the progress text can be implemented, specifically in terms of calculating the progress percentage? I'm assuming we want to track progress per file, but I'm not sure about the specifics. There is a package called [potodo](https://pypi.org/p/potodo) that can track the progress of .po files, maybe it might be relevant? Any thoughts?

Yes, `potodo` calculates total progress. There is a caveat in calculating the total progress: some translations projects don't store PO files that haven't been started translating or don't have enough progress of translation on Transifex. That inflates calculated progress as we won't count not started (missing) PO files. We could propose to add a `--compare` flag to lookup POT files as a base and compare our POs structure with POTs generated from CPython docs.

I was actually thinking of tracking total progress, at list in the first iteration. The majority of work is to be done on Sphinx side. I think static note at the top of every docs' article should be doable with [Sphinx Extensions API](https://www.sphinx-doc.org/en/master/extdev/). We also should wire up localizing the message in the note to various languages.

**Comment by JulienPalard** [comment]
Related to https://github.com/sphinx-doc/sphinx/issues/1246

**Comment by humitos** [comment]
> Should this kind of thing be implemented sphinx-side instead? It could be helpfull for anyone, not just cpython.

Yes. I'd like this to be implemented in Sphinx if possible since we need this in multiple projects I'm part of. If it's not possible to implement on Sphinx itself, it would be good to do it as an extension, so it can be easily re-used.

**Comment by m-aciek** [comment]
Related to https://github.com/sphinx-doc/sphinx/issues/11157

**Comment by AA-Turner** [comment]
The next version of Sphinx will retain the ``translated`` attribute; thanks to @humitos for the PR!

A

**Comment by humitos** [comment]
The next version of Sphinx (7.1.0) will include [the PR to keep the `translated` attribute in the nodes](https://github.com/sphinx-doc/sphinx/pull/11502). With that attribute, we can achieve all the proposal from this PR:

* include a note on top of each page mentioning the total progress of the translation
* only include a note on those pages that are not at 100%
* highlight untranslated paragraphs with a different color

On that Sphinx PR, there is a link to [an example project that uses this `translated` attribute](https://github.com/humitos/sphinx-translated-node-example/blob/main/translated.py) to:

* show the total progress of the page (it uses Sphinx substitutions for this, like `|translation-progress|`)
* highlight only translated paragraphs

I'm happy to discuss more about these ideas and work/help others to work on a Sphinx extension that all the CPython translators (and other projects too) can use and benefit from. Are there more ideas you have we should focus on? Would the CPython official documentation use an extension like this if we implement it?

**Comment by AA-Turner** [comment]
Sphinx 7.1 includes the [``|translation progress|`` substitution variable](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#substitutions) out-of-the-box, which seems like it will solve @m-aciek's original request. The new [``translation_progress_classes``](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-translation_progress_classes) configuration variable allows adding ``translated`` and/or ``untranslated`` classes to elements in each document, which can then be styled appropriatley.

A

**Comment by m-aciek** [comment]
@AA-Turner @humitos Thank you for your efforts! I've created a [Sphinx ticket](https://github.com/sphinx-doc/sphinx/issues/11537) to discuss adding a built-in extension with the functionality proposed here.

**Comment by AA-Turner** [comment]
Is there anything further to do on the docsbuild-scripts side of things? Or should this issue remain open until @m-aciek has implemented & merged his extension into Sphinx?

A

**Comment by m-aciek** [comment]
I think we can keep it open in case there is some configuration change needed on docsbuild-scripts side of things (not sure it that would be the case), though it's not a strong opinion.

> Or should this issue remain open until @m-aciek has implemented & merged his extension into Sphinx?

For what it's worth I'm afraid I won't be able to work on it at least until Christmas. Also I'm still not very familiar with Sphinx codebase, therefore I'm not sure how long it would take me.

**Comment by AA-Turner** [comment]
@m-aciek @egeakman are there any updates on this? Can we close this issue?

A

**Comment by m-aciek** [comment]
Sadly no progress on my side. I'm closing in favour of #11537 👍  We can reopen in case of any change needed here to bring it to Python docs.
