### ISSUE TITLE
Request for merge permissions: AA-Turner and hugovk

### ISSUE THREAD

**Issue by hugovk** [python/docsbuild-scripts#193]
I'd like to request merge permissions on this repo for @AA-Turner and me. We're both core devs with an interest in docs.

For example, I'd like us to be able to iterate more quickly to improve the build times: since https://github.com/python/docsbuild-scripts/issues/169 was created, we've had full builds taking over 40 hours.

We have a low bus factor here: there are currently 8 approved PRs awaiting merge. I don't know who exactly has commit rights but only Julien, Ee, Benjamin and Donald have ever merged PRs here. Can we expand it?

Thanks!

**Comment by willingc** [comment]
Is there any reason to not grant merge privileges to all core team?

**Comment by hugovk** [comment]
I also support granting merge privileges to the whole core team.

**Comment by hugovk** [comment]
@ewdurbin Is this something you can take care of: adding either us three (Adam, Carol and me), or the whole core team?

**Comment by JulienPalard** [comment]
Added @hugovk @willingc and @AA-Turner, but I don't know how to add the whole core team, I'll let @ewdurbin do it.

**Comment by hugovk** [comment]
Thank you!

**Comment by ewdurbin** [comment]
Role for Python core team moved from "read" to "maintain". I have removed the individual access for folks included in that team. I think that covers this request.
