### ISSUE TITLE
Sentry access for @hugovk @AA-Turner 

### ISSUE THREAD

**Issue by JulienPalard** [python/docsbuild-scripts#194]
Hi @hugovk @AA-Turner, do you have access to https://python-software-foundation.sentry.io/projects/python-docs ? If no you should ask @ewdurbin, it's helpfull to have live feedback when working on this script.

**Comment by ewdurbin** [comment]
I just need email addresses associated with sentry.io accounts to send invites.

**Comment by ewdurbin** [comment]
Can be sent to ee [at] python

**Comment by ewdurbin** [comment]
invites sent!
