### ISSUE TITLE
Switchers are broken

### ISSUE THREAD

**Issue by adorilson** [python/docsbuild-scripts#226]
When accessing https://docs.python.org/3/, the version switcher shows 3.14; however, the content is 3.13.

If you try to change the version or the language, you can't.

Changing the URL manually works, and you can change the version/language until 3.12.

**Comment by AA-Turner** [comment]
#227 should fix the second part, I'm currently investigating the first.

**Comment by AA-Turner** [comment]
#228 should fix the first part.

**Comment by AA-Turner** [comment]
The next rebuild is scheduled for 22:46 GMT.

**Comment by AA-Turner** [comment]
I believe this is now fixed. @adorilson do you concur?

A

**Comment by adorilson** [comment]
> I believe this is now fixed. @adorilson do you concur?
> 
> A

Yes, it does. Thank you, AA.
