### ISSUE TITLE
smart quotes breaks API reference

### ISSUE THREAD

**Issue by methane** [python/docsbuild-scripts#32]
Ref: python-doc-ja/python-doc-ja#771

When Japanese quotes (e.g. `『`, `「`) are suitable, we use them in translation.
So we don't want to translate English quotes (`"`, `'`) to Japanese quotes automatically.

Would you disable [smart-quotes](http://docutils.sourceforge.net/docs/user/config.html#smart-quotes) option in docutils.conf?

**Comment by JulienPalard** [comment]
Looks fixed in https://github.com/python/docsbuild-scripts/pull/33

**Comment by JulienPalard** [comment]
Fixed (I just upgraded sphinx to the latest version, they fixed it).

**Comment by methane** [comment]
@JulienPalard In Japanese, we want use `"` and `'` not only API manual, but also normal paragraph. For example,

> バグ報告フォームには幾つかのフィールドがあります。"Title" フィールドには、問題の説明を *非常に* 簡潔に書いてください。

Could you consider again disabling smart quotes?

https://github.com/python-doc-ja/python-doc-ja/issues/774#issuecomment-336632150

As @cocoatomo said, we can disable it by putting `docutils.conf` file like below on top of the sphinx  project root directory.

```
[restructuredtext parser]
smart_quotes:no
```

**Comment by methane** [comment]
https://github.com/python-doc-ja/python-doc-ja/issues/774#issuecomment-336690440

@cocoatomo suggests this configuration for `docutils.conf`:

```
[restructuredtext parser]
smartquotes_locales: ja: ""''
```

With this config, `"title"` is used for Japanese and `«title»` is used for French.

**Comment by JulienPalard** [comment]
That's nice, so we can commit the file in cpython if this is the case, I'm trying it right now.

**Comment by JulienPalard** [comment]
I tried it and got the following results:

No diff for en and fr as expected, and a diff for japanese as following:
Lots of:
```
< zip application format uses this ability to prepend a standard POSIX 「shebang」
---
> zip application format uses this ability to prepend a standard POSIX &quot;shebang&quot;
```

and
```
< <em>mainfn</em> 引数は 「pkg.mod:fn」 の形式で指定します。
< 「pkg.mod」 の場所はアーカイブ内の package/module です。
< 「fn」 は指定した module から呼出すことのできる関数です。
---
> <em>mainfn</em> 引数は &quot;pkg.mod:fn&quot; の形式で指定します。
> &quot;pkg.mod&quot; の場所はアーカイブ内の package/module です。
> &quot;fn&quot; は指定した module から呼出すことのできる関数です。
```

I'm opening an issue on b.p.o and a PR.

**Comment by JulienPalard** [comment]
Opened the PR: https://github.com/python/cpython/pull/4006

**Comment by JulienPalard** [comment]
https://github.com/python/cpython/pull/4006 has been merged.

**Comment by cocoatomo** [comment]
Same issue is now occurring on Japanese translation.

> バグ報告フォームには幾つかのフィールドがあります。」Title」 フィールドには、問題の説明を 非常に 簡潔に書いてください。
https://docs.python.org/ja/3/bugs.html

docutils.conf does exist on https://github.com/python/cpython/blob/master/Doc/docutils.conf,
but it does not seem effective.

I would like to reopen this issue.

**Comment by cocoatomo** [comment]
@JulienPalard Would you like to check the comment above?

**Comment by JulienPalard** [comment]
Hi @cocoatomo, I tried disabling smartquotes completly, on `bugs.html` diffs are:

```
< 『docs&#64;』 はボランティアによって運営されているメーリングリストです。
---
> 'docs&#64;' はボランティアによって運営されているメーリングリストです。
113,116c113,116
< <p>問題がまだバグトラッカーに登録されていない場合は、Python Bug Tracker のトップページに戻ってログインしてください。まだトラッカーのアカウントをもっていない場合は、サイドバーの 「Register」 リンクを選んでください。また、OpenID を使っている場合はサイドバーの OpenID プロバイダのロゴをクリックしてください。匿名での問題報告はできません。</p>
< <p>ログインできたら、バグを登録できます。サイドバーの 「Create New」 リンクからバグ報告フォームを開きます。</p>
< <p>バグ報告フォームには幾つかのフィールドがあります。」Title」 フィールドには、問題の説明を <em>非常に</em> 簡潔に書いてください。10語以下くらいが目安です。」Type」 フィールドでは、問題の種類を選択してください。バグに関係する 「Component」 と 「Versions」 も選択してください。</p>
< <p>「Comment」 フィールドで、あなたが期待した結果と実際の結果も含め、問題の詳細を説明してください。拡張モジュールが関与しているかどうかと、使用しているハードウェアとソフトウェアプラットフォームも (必要に応じてバージョン情報も) 必ず報告に含めてください。</p>
---
> <p>問題がまだバグトラッカーに登録されていない場合は、Python Bug Tracker のトップページに戻ってログインしてください。まだトラッカーのアカウントをもっていない場合は、サイドバーの &quot;Register&quot; リンクを選んでください。また、OpenID を使っている場合はサイドバーの OpenID プロバイダのロゴをクリックしてください。匿名での問題報告はできません。</p>
> <p>ログインできたら、バグを登録できます。サイドバーの &quot;Create New&quot; リンクからバグ報告フォームを開きます。</p>
> <p>バグ報告フォームには幾つかのフィールドがあります。&quot;Title&quot; フィールドには、問題の説明を <em>非常に</em> 簡潔に書いてください。10語以下くらいが目安です。&quot;Type&quot; フィールドでは、問題の種類を選択してください。バグに関係する &quot;Component&quot; と &quot;Versions&quot; も選択してください。</p>
> <p>&quot;Comment&quot; フィールドで、あなたが期待した結果と実際の結果も含め、問題の詳細を説明してください。拡張モジュールが関与しているかどうかと、使用しているハードウェアとソフトウェアプラットフォームも (必要に応じてバージョン情報も) 必ず報告に含めてください。</p>
130c130
< <p>見つけたバグの報告だけでなく、修正パッチの提出も歓迎します。<a class="reference external" href="https://devguide.python.org/">Python Developer’s Guide</a> には Python へのパッチの始め方について詳しい情報があります。疑問があれば、<a class="reference external" href="https://mail.python.org/mailman/listinfo/core-mentorship/">core-mentorship mailing list</a> は Python の問題解決の過程に関するありとあらゆる疑問への答えを得ることが出来るフレンドリーな場所です。</p>
---
> <p>見つけたバグの報告だけでなく、修正パッチの提出も歓迎します。<a class="reference external" href="https://devguide.python.org/">Python Developer's Guide</a> には Python へのパッチの始め方について詳しい情報があります。疑問があれば、<a class="reference external" href="https://mail.python.org/mailman/listinfo/core-mentorship/">core-mentorship mailing list</a> は Python の問題解決の過程に関するありとあらゆる疑問への答えを得ることが出来るフレンドリーな場所です。</p>
```

(Last one diff on the simple quote of "Developer's" from U+2019 to U+0027.)

How does it looks to you?

Sadly it diff a lot on english and french version too (U+2019, U+201C, U+201D, ...).

**Comment by cocoatomo** [comment]
That result looks good, but disabling smartquotes has bad effect on French version, which is quite undesirable for me.

So, I suggest to use configuration [smartquotes_excludes](http://www.sphinx-doc.org/ja/1.7/config.html#confval-smartquotes_excludes) in conf.py.
This configuration is more straightforward and flexible than `smartquotes-locales` in docutils.conf.

**Comment by JulienPalard** [comment]
So, upgrading to sphinx 1.6.6 should do it. I'm trying a local build with 1.7.2.

**Comment by cocoatomo** [comment]
Since this commit bumps Sphinx version to 1.7.2, smartquotes was disabledfor Japanese HTML builds and will not break Japanese HTML documents.
Of course, smartquotes is still enabled for other language.

Finally, this issue seems resolved with the better way.

**Comment by JulienPalard** [comment]
Nice to hear :)
