### ISSUE TITLE
Handle /release/ directory

### ISSUE THREAD

**Issue by JulienPalard** [python/docsbuild-scripts#48]
docsbuild-scripts could manage the /release/ directory too, this directory is currently manually handled by RMs, see [PEP 101](https://www.python.org/dev/peps/pep-0101/).

**Comment by JulienPalard** [comment]
## www.python.org/ftp/python/doc/

- Maintained manually by release managers.
- Contains a `current/` directory pointing to the current stable release.
- Each directory contains an epub file and tarballs and zipfiles of: pdf-a4, pdf-letter, epub, html, texinfo and text.


## www.python.org/doc/versions/

Contains links to http://docs.python.org/release/x.x.x/ for each release, updated manually by release managers.


## Download pages in docs.python.org/releases/

In those download pages, download links looks like:

https://docs.python.org/ftp/python/doc/3.6.2/python-3.6.2-docs-pdf-letter.zip

which are just redirections to:

https://www.python.org/ftp/python/doc/3.6.2/python-3.6.2-docs-pdf-letter.zip

This is the result of the `daily` flag:
```

{% if daily is defined %}
   {% set dlbase = pathto('archives', 1) %}
{% else %}
   {% set dlbase = 'https://docs.python.org/ftp/python/doc/' + release %}
{% endif %}
```

**Comment by AA-Turner** [comment]
`/release/` is now handled automatically by [`run_release.py`](https://github.com/python/release-tools/blob/7814f13dd1a20476ae9407d23e80d4b87623ff46/run_release.py#L786-L816).

A
