### ISSUE TITLE
Add/document a way to purge a whole release after modifying a symlink

### ISSUE THREAD

**Issue by JulienPalard** [python/docsbuild-scripts#49]
Currently, when a RM changes a symlink, like `ln -nfs 3 3.7.0` (to make /3/ point to 3.7), there's no (documented) way to invalidate the cache for `/3/*`.

**Comment by AA-Turner** [comment]
Closed by 9a01f7fd2e3f3f602fb78c139e96ea8f13564dca and b3c3137efb04c789a60b4ceb65fbb0ad46370f4b.

A
