### ISSUE TITLE
Build old releases, at least for translations.

### ISSUE THREAD

**Issue by JulienPalard** [python/docsbuild-scripts#51]
Today, 3.5 is typically never built. But translations are indirectly contributing to it so we may still build it, from time to time.

An idea is to monitor the repositories and build only when necessary.

**Comment by JulienPalard** [comment]
Check if by fixing that, our old releases like https://docs.python.org/3.4/tutorial/appetite.html will get a canonical to /3/ like 3.5 currently has.

**Comment by AA-Turner** [comment]
I don't think this is a priority currently -- we rebuild all languages for every supported version, which will have the most traffic.

A
