### ISSUE TITLE
Build a sitemap

### ISSUE THREAD

**Issue by JulienPalard** [python/docsbuild-scripts#56]
It would probably be nice if we can generate a sitemap of our documentations.

**Comment by devarshigoswami** [comment]
@JulienPalard has this issue been resolved? if not, can I work on it?

**Comment by JulienPalard** [comment]
This has not been resolved, you're welcome working on it :) Please check first if it already exist as a part of sphinx, let's not reinvent the wheel (haven't checked myself).

**Comment by devarshigoswami** [comment]
@JulienPalard I checked .. couldn't find anything referencing `docsbuild-scripts` in the sphinx documentation. Also, I'm a tad new to this hence a little more information would be really appreciated... Do you want me to build an XML sitemap for docs.python.org or am I completely understanding the task wrongly?

**Comment by JulienPalard** [comment]
docsbuild-scripts uses Sphinx, but Sphinx don't know docsbuild-scripts.

Sphinx is a tool to build documentation from rst files.

docsbuild-scripts is a tool to call Sphinx multiple times: Once per Python version and per supported language, with specific parameters (though "config-variables" at the top of the script).

The output of docsbuild-script is hosted at https://docs.python.org, it's started daily: https://github.com/python/psf-salt/blob/master/salt/docs/init.sls#L83-L91

So https://docs.python.org/fr/3.8/ is one sphinx build. https://docs.python.org/fr/3.7/ is another one, https://docs.python.org/ja/3.8/ is another one, and so on, and so on.

Beware, running a full docsbuild-scripts takes some time, and some disk space, as it'll build *n* languages times *m* versions.

The idea behind this issue is to provide a sitemap to all generated content across all builds.

The strategy I have in mind is: have a "sitemap index" listing sitemaps of individual builds, and a sitemap per build.

**Comment by JulienPalard** [comment]
We now have a very minimal sitemap: https://docs.python.org/sitemap.xml :)
