### ISSUE TITLE
Don't use `-W` to build unmaintained translations.

### ISSUE THREAD

**Issue by JulienPalard** [python/docsbuild-scripts#63]
Currently we're using `sphinx-build -W` to spot errors, but on unmaintained translations like 3.8, as we're using the po files from 3.7, it's normal to have inconsistencies.

Maybe we should detect we're using files from another version and just drop the `-W` in this case.

**Comment by AA-Turner** [comment]
Closed in 144f8c81ac33caf99c9224109d8cb22d47b8f475.

A
