### ISSUE TITLE
404 in archives/ during new releases

### ISSUE THREAD

**Issue by JulienPalard** [python/docsbuild-scripts#68]
On the release of 3.7.2rc1, the archives/ were not built automatically (they are built daily).

I bet (didn't checked it yet) that it should fix itself in less than 24h, while the cron passes, but it's too long and it bothers people.

I had to build locally then from the local `www/` directory run:

```
$ rsync -vrhi --include '/*/' --include '/*/*.*/' --include '/*/*.*/archives/' --include '/*/*.*/archives/**' --exclude '*' ./ docs.iad1.psf.io:/srv/docs.python.org/
```

Then remotely run:
```
$ sudo chown docsbuild:docs /srv/docs.python.org/*/*/archives/*
$ cd /srv/docs.python.org/; for file in */*/archives/*; do  curl -XPURGE https://docs.python.org/$file; done
```

to temporary trash-fix this.

**Comment by JulienPalard** [comment]
For the record, it happened again on the 3.7.2 release. I fixed it manually again using the previous commands (just changed the versions).

**Comment by JulienPalard** [comment]
Another way to do it is to start manually a build_docs right after a release:
```
docsbuild@docs:~$ /srv/docsbuild/venv/bin/python /srv/docsbuild/scripts/build_docs.py -b 3.8 --languages en
```

**Comment by Mariatta** [comment]
Not sure how it all work.. can we not display the new download URLs before the downloadables have finished getting built?

**Comment by JulienPalard** [comment]
@Mariatta that's an idea.

The issue is we're building HTML multiple time a day, but PDF only once a day, so it happen that some release get their HTML build before their PDF.

**Comment by Mariatta** [comment]
What is needed to ensure that both PDF and HTML get built at release time, instead of waiting for the cron to run?

**Comment by JulienPalard** [comment]
There's https://github.com/python/docsbuild-scripts/issues/77 that should have the side effect to solve it, by running the build only when needed it could rebuild everything. But it's a lot of work and I did not found the free time to do it.

A simple solution in the meantime would be to stop the cron building HTML only, keeping only daily full builds (html + pdf), I don't think we need the HTML doc to be updated every 3 hours, what do you think?

**Comment by Mariatta** [comment]
I think building them once a day sounds good and could reduce the number of 404 reports we're getting. And we are certain that by the time the HTML is done building. and rendered, the PDFs are also finished?

**Comment by JulienPalard** [comment]
Closing as it does no longer happen, as we do no longer use the quick builds.
