### ISSUE TITLE
CJK PDF missing characters

### ISSUE THREAD

**Issue by zhsj** [python/docsbuild-scripts#71]
Actually all CJK{Chinese, Japanese, Korean} PDF are not generated correctly.

The Chinese PDF should be fixed with #70 

But I'm not sure what to do with Japanese and Korean. `xeCJK` is supposed to work for all CJK. But it's best to have some native developer/translator to check it.

**Comment by JulienPalard** [comment]
Since #70 is merged, here's what I see in the logs

```
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo)))
(/usr/share/texlive/texmf-dist/tex/latex/cmap/cmap.sty

Package cmap Warning: pdftex not detected - exiting.

)

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.15 u
      sepackage{xeCJK}
? 
! Emergency stop.
 ...                                              
                                                  
l.15 u
      sepackage{xeCJK}
No pages of output.
Transcript written on howto-curses.log.
Latexmk: Log file says no output from latex
Latexmk: For rule 'pdflatex', no output was made

```

**Comment by zhsj** [comment]
Just confirm that the zh-cn pdf looks good now.

But zh-tw it still broken since the default fandol font has a limited support for Tranditional Chinese font... However it's better than previous, which doesn't have any Chinese characters.

ko is broken as before.

ja looks good with platex.

**Comment by hugovk** [comment]
Is this fixed after the merge of https://github.com/python/python-docs-ko/issues/595?
