### ISSUE TITLE
Move indexsidebar.html and switchers.js to docsbuild-scripts

### ISSUE THREAD

**Issue by JulienPalard** [python/docsbuild-scripts#90]
The idea is that the cpython Doc/ repository should just care about building the documentation, not linking to other builds and languages from docs.python.org.

Building multiple versions, multiple languages, and linking them together is the role of docsbuild-scripts.

This would also avoid the need to update `switchers.js` and `indexsidebar.html` on every cpython branch for every new cpython release and every new language.

What would need to change:

- Drop `switchers=1` from `cpython/Doc/Makefile`
- Drop `if switchers` block in `cpython/tools/templates/layout.html`. it already has an alternative. Add an `id` to the `<li>` so it can be easily found by the new `switchers.js` as the placeholders are dropped.
- Move `switchers.js` to docsbuild-scripts and make it use the `<li>` new id instead of placeholders if they are not found, and maybe fallback to find the place from other ways so it can work on old branches without commiting to them.
- Write a generic "indexsidebar.html" for local builds, to be commited in cpython, and move the "cross-linked" version of indexsidebar in docsbuild-scripts.
- Move {% trans %} tags in dummy.html so they can still be translated even if versionned in docsbuild-scripts (it's the only remaining part in cpython, hope it won't change too often).

We then need a **clean** way for docsbuild-scripts to edit the HTML to make it load switchers.js.

**Comment by ned-deily** [comment]
I like this idea a lot.

I'm not sure what you are suggesting replacing the index sidebar with
for the standalone build.  But perhaps rather than the current links to
and status of recent branches, it could have a few generic links to
the docs on the website, something like:

stable -> https://docs.python.org/
in development -> https://docs.python.org/dev/
all versions -> https://www.python.org/doc/versions/
more resources -> https://www.python.org/doc/

**Comment by JulienPalard** [comment]
It now works for me, I'll merge it later to let time for potential reviewers.

Listing tasks to be done in case it gets merged:

- [ ] Review https://www.python.org/dev/peps/pep-0101/ to remove steps like `Doc/tools/static/switchers.js must be updated`.
- [ ] Clean the master branch to remove everything about switchers and add @ned-deily proposed links to the sidebar instead of hardcoded links to other versions

**Comment by JulienPalard** [comment]
Done.
