### ISSUE TITLE
Update Sphinx to 2.4.4

### ISSUE THREAD

**Issue by vstinner** [python/docsbuild-scripts#95]
The Python 3.8 and 3.9 documentation is now built with Sphinx 2.4.4 to fix warnings:
https://bugs.python.org/issue35293

The Python 3.10 documentation is built with Sphinx 3.2.1.

Can we update Sphinx to 2.4.4, to stay in sync?

**Comment by vstinner** [comment]
cc @JulienPalard @ned-deily @corona10

**Comment by JulienPalard** [comment]
done.

**Comment by vstinner** [comment]
@JulienPalard: Great! Thank you!
