### ISSUE TITLE
Please update https://docs.python.org/dev/ more frequently than once a day

### ISSUE THREAD

**Issue by vstinner** [python/docsbuild-scripts#98]
Yesterday, I rewrote a large part of the documentation. I merged my PR. One hour later, I expected to see it online to validate the rendered HTML, but it was outdated. The day after? It's still outdated. @JulienPalard told me that it's updated once a day.

Would it be possible to rebuild https://docs.python.org/dev/ more frequently? For example, every hour? Or even at each commit? Every hour would be fine with me.

For curious people, my doc change: https://github.com/python/cpython/commit/4b9aad49992a825d8c76e428ed1aca81dd3878b2

**Comment by shihai1991** [comment]
+1 for `even at each commit`

**Comment by vstinner** [comment]
I would be fine with anything more frequent than once a day. For example, One per hour would be great :-)

I don't require to have a new build per commit.

**Comment by vstinner** [comment]
Thank you @JulienPalard and @ewdurbin!

**Comment by JulienPalard** [comment]
@vstinner it's merged but not plugged to github yet, I'll take a few config steps.
